# Generated by Django 5.2.4 on 2025-07-16 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("episodios", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assistindo", "Assistindo"),
                            ("assistido", "Assistido"),
                            ("pendente", "Pendente"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("episodioAtual", models.IntegerField(default=0)),
                ("nota", models.IntegerField(default=0)),
            ],
        ),
    ]
